### ISSUE TITLE
ibmcloud cf push app name  error

### ISSUE THREAD

**Issue by kellytron80** [IBM/virtual-mirror-for-ecommerce#10]
Hello,

Thanks once again for the good work. I am a developer and trying to develop an app following the steps in the virtual mirror ecommerce code patterns issued through https://developer.ibm.com/code/patterns. After cloning the repository and following all steps i am stucked at having a problem when trying to run the command ibmcloud cf push "my app name". I always get the error failed. What could likely be the problem or is the code still updated?

Thanks

**Comment by bharathimani25** [comment]
Getting error while pushing App. unbound Local Error is projected with local variable 'gender' referenced before assignment

**Comment by kellytron80** [comment]
Hello,

i dont understand. I get this error when i run cf logs "my app name" Attached is the screenshot

Thanks
![Screenshot (80)](https://user-images.githubusercontent.com/34573957/75701147-8b0ce180-5cb3-11ea-99b1-3cd7a2f83d4c.png)
