### ISSUE TITLE
While running app in mobile the recommendation eng keeps on loading. It throws like vitual mirror not configured

### ISSUE THREAD

**Issue by bharathimani25** [IBM/virtual-mirror-for-ecommerce#14]

**Comment by RahulReddyRavipally** [comment]
Hi @bharathimani25, we have updated the documentation. Seems like you have missed out some steps. Make sure you follow the documentation and perform all the steps from 1 to 4. We have tested and validated entire pattern. It works fine.

I would also recommend you to take a look at the troubleshooting guide : https://github.com/IBM/virtual-mirror-for-ecommerce/blob/master/TROUBLESHOOTING.md
